### ISSUE TITLE
ROADMAP.md is empty

### ISSUE THREAD

**Issue by emilyastranova** [Memotic/async-translate#2]
Thats the issue

**Comment by fredster33** [comment]
Hey @tyleraharrison , thanks for opening this issue. Async Translate is still in its infancy, so many parts of the documentation might be empty, however, we’re working on adding to them.

Answering with my hat as Mr. Translate Regulator

**Comment by emilyastranova** [comment]
I figured, just thought it would be funny to send an issue to Will's repository 😊
